import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ASSETS_DIR = path.resolve(__dirname, '../assets/hytale');
const OUTPUT_FILE = path.resolve(__dirname, '../src/worker/services/hytale/cosmetic-assets-manifest.ts');

function getFiles(dir: string): string[] {
	const subdirs = fs.readdirSync(dir);
	const files = subdirs.map((subdir) => {
		const res = path.resolve(dir, subdir);
		return fs.statSync(res).isDirectory() ? getFiles(res) : res;
	});
	return files.flat();
}

async function generateManifest() {
	console.log(`Scanning assets in ${ASSETS_DIR}...`);

	// Find all asset files recursively
	const allFiles = getFiles(ASSETS_DIR);
	const files = allFiles.filter(f => /\.(blockymodel|blockyanim|png)$/.test(f));

	console.log(`Found ${files.length} assets.`);

	const imports: string[] = [];
	const mapping: string[] = [];

	for (const [index, absPath] of files.entries()) {
		// Relative path from ASSETS_DIR
		const relPath = path.relative(ASSETS_DIR, absPath).replaceAll('\\', '/');

		// Create a unique variable name
		const varName = `asset_${index}`;

		// Relative path for import (from src/worker/services/hytale/)
		// assets/hytale is at ../../../../assets/hytale
		const importPath = `../../../../assets/hytale/${relPath}`;

		imports.push(`import ${varName} from '${importPath}';`);

		mapping.push(`  '${relPath}': ${varName},`);
	}

	const content = `/**
 * Auto-generated manifest of Hytale assets
 * Generated by scripts/generate-manifest.ts
 */

${imports.join('\n')}

export const ASSET_MANIFEST: Record<string, any> = {
${mapping.join('\n')}
};
`;

	fs.writeFileSync(OUTPUT_FILE, content);
	console.log(`Manifest written to ${OUTPUT_FILE}`);
}

generateManifest().catch(console.error);
